# Generated by Django 5.0.4 on 2024-04-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='media/photos')),
                ('descreption', models.TextField()),
                ('price', models.CharField(max_length=60)),
                ('weight', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('submenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='products.submenu')),
            ],
        ),
    ]
